version: "3.9"
services:

  redis:
    image: redis:6.2.6-alpine
    env_file:
      - compose/development/.env

  authentication:
    build:
      context: .
      dockerfile: compose/development/Dockerfile
    image: authentication_image
    command: /start-authentication
    env_file:
      - compose/development/.env
    ports:
      - '8000:8000'
    volumes:
      - .:/authentication
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.7.1
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - compose/development/.env

  celery_worker:
    build:
      context: .
      dockerfile: compose/development/Dockerfile
    image: authentication_celery_worker_image
    command: /start-celery-worker
    volumes:
      - .:/authentication
    env_file:
      - compose/development/.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: compose/development/Dockerfile
    image: authentication_celery_beat_image
    command: /start-celery-beat
    volumes:
      - .:/authentication
    env_file:
      - compose/development/.env
    depends_on:
      - redis
      - db

  celery_flower:
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    image: authentication_celery_flower_image
    command: /start-celery-flower
    volumes:
      - .:/authentication
    env_file:
      - ./compose/development/.env
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - db


volumes:
  mariadb-data:
