[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_third_party = ["celery", "django", "drf_yasg", "requests", "rest_framework", "rest_framework_simplejwt"]
known_first_party = []
