#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

mariadb_ready() {
python << END
import sys

import MySQLdb
from MySQLdb._exceptions import OperationalError

try:
    MySQLdb.connect(
        host="${MARIADB_HOST}",
        user="${MARIADB_USER}",
        passwd="${MARIADB_PASSWORD}",
        db="${MARIADB_DATABASE}",
        port=${MARIADB_PORT}
    )
except OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until mariadb_ready; do
  >&2 echo 'Waiting for MariaDB to become available...'
  sleep 1
done
>&2 echo 'MariaDB is available'

exec "$@"
